native show_life(index)

native set_life( index, lifes )
native cs_get_user_money_ul(index)
native cs_set_user_money_ul(index, money, flash = 1)
native get_user_exp(index)

/////Бронь террориста//////////
native show_ter(index)
///////////////////////////////

native dr_get_user_level(id)
native dr_set_user_level(id, amount)

native dr_get_user_exp(id)
native dr_set_user_exp(id, amount)

native dr_get_user_coin(id)
native dr_set_user_coin(id, amount)

native win_money_big(id)
native dr_narkotiki(id)

