gfx/env/52h05bk.tga
gfx/env/52h05dn.tga
gfx/env/52h05ft.tga
gfx/env/52h05lf.tga
gfx/env/52h05rt.tga
gfx/env/52h05up.tga
sprites/laserbeam.spr
models/w_ak47.mdl
models/w_awp.mdl
models/w_m4a1.mdl
models/w_m249.mdl
models/w_m3.mdl
models/brgames_maps/Kuctik2.mdl
models/brgames_maps/gh_tree2.mdl
sound/brgames_music/balao.wav
sound/brgames_music/wilson.wav
sound/brgames_music/suvacocabeludo.wav
sound/brgames_music/olhaogol.wav
maps/jail_revolution_v3_brgames.res
maps/jail_revolution_v3_brgames.bsp

